import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  RBAC_ROLE_DENIED: 'RBAC_ROLE_DENIED',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACTIVITY_CATEGORY_INVALID: `ACTIVITY_CATEGORY_INVALID:${Object.values(ActivityCategory).join('|')}`,
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  FACTOR_NOT_FOUND: 'FACTOR_NOT_FOUND',
  FACTOR_VERSION_DUPLICATE: 'FACTOR_VERSION_DUPLICATE',
  FACTOR_DATE_INVALID: 'FACTOR_DATE_INVALID',
  GOAL_STATUS_INVALID: `GOAL_STATUS_INVALID:${Object.values(GoalStatus).join('|')}`,
  DATABASE_FAILED: 'DATABASE_FAILED'
} as const;

